packages:
  - "apps/*"
  - "packages/*"
allowBuilds:
  '@apollo/protobufjs': true
  '@prisma/engines': true
  argon2: true
  esbuild: true
  msgpackr-extract: false
  prisma: true
  unrs-resolver: true
  workerd: false
pmOnFail: ignore